server:
    port: 8888

syj-rateLimit:
  db: redis
    #algorithm: token
spring:
  redis:
    host: 10.0.20.
    port: 7000
    password:
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 1000
