server:
    port: 8888

syj-rateLimit:
  algorithm: token
  db: redis

spring:
  datasource:
    url: jdbc:mysql://10.0.20:3306/ApolloConfigDB?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 500
    initialSize: 100
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 200
  redis:
    host: 10.0.20.120
    port: 7000
    password: unicode!@#
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 1000

